import type { Metadata } from "next";

import { Inter } from "next/font/google";
import localfont from "next/font/local";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";

import "./globals.css";
import AppProvider from "./lib/provider/app";
import Header from "./lib/design/layout/header";

const iranSans = localfont({ src: "../public/fonts/iranSans.woff2" });

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl">
      {/* className={`${iranSans.className} bg-gray-100 text-black  
        dark:bg-black dark:text-white capitalize`} */}
      <body
        className={`${iranSans.className} bg-gray-100 text-black dark:bg-black dark:text-white capitalize`}
      >
        <Header />
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
